// flow-typed signature: 1e549eef81fc8aa85fad4a1dcd5d8673
// flow-typed version: <<STUB>>/doc-cookies_v1.0.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'doc-cookies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'doc-cookies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'doc-cookies/docCookies' {
  declare module.exports: any;
}

declare module 'doc-cookies/docCookies.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'doc-cookies/docCookies.js' {
  declare module.exports: $Exports<'doc-cookies/docCookies'>;
}
declare module 'doc-cookies/docCookies.umd.js' {
  declare module.exports: $Exports<'doc-cookies/docCookies.umd'>;
}
