// @flow

export const DELETE_VERSION_PENDING = 'vb/DELETE_VERSION_PENDING';
export const DELETE_VERSION_SUCCESS = 'vb/DELETE_VERSION_SUCCESS';
export const DELETE_VERSION_FAILURE = 'vb/DELETE_VERSION_FAILURE';
