// @flow

export const GET_DOCUMENT_ID_PENDING = 'vb/GET_DOCUMENT_ID_PENDING';
export const GET_DOCUMENT_ID_SUCCESS = 'vb/GET_DOCUMENT_ID_SUCCESS';
export const GET_DOCUMENT_ID_FAILURE = 'vb/GET_DOCUMENT_ID_FAILURE';
