// @flow

export const LOGOUT_PENDING = 'vb/LOGOUT_PENDING';
export const LOGOUT_SUCCESS = 'vb/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'vb/LOGOUT_FAILURE';

export const CREATE_VERSION_PENDING = 'vb/CREATE_VERSION_PENDING';
export const CREATE_VERSION_SUCCESS = 'vb/CREATE_VERSION_SUCCESS';
export const CREATE_VERSION_FAILURE = 'vb/CREATE_VERSION_FAILURE';
